-- 将该建表 SQL 语句，添加到 yudao-module-hrsys-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "hrsys_client" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "client_type" varchar,
    "client_name" varchar NOT NULL,
    "client_address" varchar,
    "contact" varchar,
    "contact_phone" varchar,
    "remark" varchar,
    "group_id" bigint,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "status" int NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '客户表';